[package]
  cjc-version = "1.0.5"
  name = "ecsFramework"
  description = "nothing here"
  version = "1.0.0"
  output-type = "executable"
  compile-option = "-O2 --fast-math --int-overflow wrapping -Woff unused --diagnostic-format=noColor"
  override-compile-option = ""
  link-option = ""
  [package.package-configuration]

[dependencies]
  [dependencies.ecsmacros]
    path = "./macros"
